# Generated by Django 3.1.7 on 2021-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmApp', '0002_auto_20210531_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='BePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharm_name', models.CharField(max_length=255, verbose_name='Название вашей аптеки')),
                ('pharm_email', models.CharField(max_length=255, verbose_name='Почта вашей аптеки')),
                ('pharm_phone', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('recommendations', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='illness',
            name='description',
        ),
        migrations.AddField(
            model_name='drugs',
            name='ii_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='illness',
            name='illness_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
