# Generated by Django 3.2.4 on 2021-06-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PharmApp', '0004_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='drug_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmApp.drugs', verbose_name='Нужные лекарствы'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_Address',
            field=models.CharField(max_length=255, verbose_name='Ваш адрес'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_city',
            field=models.CharField(max_length=255, verbose_name='Ваш город'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_email',
            field=models.CharField(max_length=255, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_tel',
            field=models.CharField(max_length=255, verbose_name='Ваш телефон'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_wish',
            field=models.TextField(verbose_name='Пожелания для доставки'),
        ),
    ]
