# Generated by Django 3.2.4 on 2021-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmApp', '0006_alter_drugs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='drug_name',
            field=models.CharField(max_length=255),
        ),
    ]
