# Generated by Django 3.2.4 on 2021-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmApp', '0007_auto_20210617_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='drug_name',
            field=models.CharField(max_length=255, verbose_name='Needed chemicals'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_Address',
            field=models.CharField(max_length=255, verbose_name='Enter your home address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_city',
            field=models.CharField(max_length=255, verbose_name='Enter your city'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_email',
            field=models.CharField(max_length=255, verbose_name='Enter your email:'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_name',
            field=models.CharField(max_length=255, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person_tel',
            field=models.CharField(max_length=255, verbose_name='Enter your telephone number'),
        ),
    ]
